version: '3.8'

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        environment:
            - DB_HOST=db
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DB_NAME=tasksdb
            - DB_PORT=5432
        ports:
            - "3000:3000"
        depends_on:
            - db
        networks:
            - app-network

    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: tasksdb
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./db-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - app-network
        ports:
            - "5432:5432"

volumes:
    postgres_data:

networks:
    app-network:
        driver: bridge
